@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit"
echo Renaming branch...
git branch -M main
echo Adding remote...
git remote remove origin 2>nul
git remote add origin https://github.com/sarvast/Caloriv-web.git
echo Pushing...
git push -u origin main
echo Done.
pause
